const fs = require('fs');
const path = require('path');
const { blobDecode } = require('../blob');

describe('Blob Decoding', () => {
    test('should decode test_loopback.blob from C unit test', () => {
        // Path to the blob file generated by C unit test
        const blobPath = path.resolve(__dirname, '../../blob/build/test_loopback.blob');

        if (!fs.existsSync(blobPath)) {
            console.warn("Skipping test: test_loopback.blob not found. Run C unit tests first.");
            return;
        }

        const buffer = fs.readFileSync(blobPath);

        // Convert Node Buffer to ArrayBuffer for blob.js
        const arrayBuffer = buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);

        const [remainder, out, nodename] = blobDecode(arrayBuffer);

        expect(nodename).toBe('root');
        expect(out).toBeDefined();

        // Check contents
        // Structure: root -> test_int (12345)
        // blobDecode returns: { test_int: [ Int32Array([12345]) ] }
        // It wraps values in arrays because of repetitions?

        expect(out['test_int']).toBeDefined();
        expect(out['test_int'][0][0]).toBe(12345);
    });
});
